version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-locaprinter}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-locaprinter}
      POSTGRES_DB: ${DB_NAME:-locaprinter}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app_network

volumes:
  redis_data:
  postgres_data:
  minio_data:

networks:
  app_network:
    driver: bridge
